class MeshToPSCommand:
   CommandNameLabel="MeshToPS"
   PolygonMeshIdLabel="PolygonMeshId"
   DivideLengthLabel="DivideLength"
   ParticleSystemIdLabel="ParticleSystemId"
class MeshToVoxelCommand:
   CommandNameLabel="MeshToVoxelCommand"
   PolygonMeshIdLabel="PolygonMeshId"
   VoxelIdLabel="VoxelId"
   DivideLengthLabel="DivideLength"
class SparseVolumeNodeSetCommand:
   CommandNameLabel="SparseVolumeNodeSet"
   SparseVolumeIdLabel="SparseVolumeId"
   IndicesXLabel="IndicesX"
   IndicesYLabel="IndicesY"
   IndicesZLabel="IndicesZ"
   ValuesLabel="Values"
class SparseVolumeSceneCreateCommand:
   CommandNameLabel="SparseVolumeSceneCreate"
   ResolutionXLabel="ResolutionX"
   ResolutionYLabel="ResolutionY"
   ResolutionZLabel="ResolutionZ"
   BoundingBoxLabel="BoundingBox"
   NameLabel="Name"
   NewIdLabel="NewId"
class VoxelGetCommand:
   CommandNameLabel="VoxelGet"
   VoxelIdLabel="VoxelId"
   ResolutionXLabel="ResX"
   ResolutionYLabel="ResY"
   ResolutionZLabel="ResZ"
   BoundingBoxLabel="BoundingBox"
   ValuesLabel="Values"
class VoxelizerCommand:
   CommandNameLabel="VoxelizerCommand"
   MeshIdLabel="MeshId"
   VoxelIdLabel="VoxelId"
   DivideLengthLabel="DivideLength"
class VoxelSceneCreateCommand:
   CommandNameLabel="VoxelSceneCreate"
   ResolutionXLabel="ResolutionX"
   ResolutionYLabel="ResolutionY"
   ResolutionZLabel="ResolutionZ"
   BoundingBoxLabel="BoundingBox"
   NameLabel="Name"
   NewIdLabel="NewId"
class VoxelSetCommand:
   CommandNameLabel="VoxelNodeSet"
   VoxelIdLabel="VoxelId"
   ResolutionXLabel="ResolutionX"
   ResolutionYLabel="ResolutionY"
   ResolutionZLabel="ResolutionZ"
   BoundingBoxLabel="BoundingBox"
   ValuesLabel="Values"
class VoxelToPSCommand:
   CommandNameLabel="VoxelToPSCommand"
   VoxelIdLabel="VoxelId"
   PSIdLabel="PSId"
